#!/usr/bin/env python3
"""Generate deterministic, artifact-hashed Windows dependency locks."""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import subprocess
import sys
import tempfile
import zipfile
from dataclasses import dataclass
from email.parser import Parser
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
INPUT_PATH = REPO_ROOT / "requirements.in"
LOCK_ROOT = REPO_ROOT / "locks"
PYTHON_TAGS = ("311", "312", "313", "314")
ARCHITECTURES = {
    "x64": "win_amd64",
    "x86": "win32",
    "arm64": "win_arm64",
}
PIN_RE = re.compile(r"^([A-Za-z0-9_.-]+)==([A-Za-z0-9_.+!-]+)$")


def normalize_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


@dataclass(frozen=True)
class Artifact:
    name: str
    version: str
    filename: str
    sha256: str


def read_input_pins(path: Path = INPUT_PATH) -> dict[str, tuple[str, str]]:
    pins: dict[str, tuple[str, str]] = {}
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        match = PIN_RE.fullmatch(line)
        if not match:
            raise ValueError(f"{path}:{line_number}: dependency must use an exact == pin")
        display_name, version = match.groups()
        normalized = normalize_name(display_name)
        if normalized in pins:
            raise ValueError(f"{path}:{line_number}: duplicate dependency {display_name}")
        pins[normalized] = (display_name, version)
    if not pins:
        raise ValueError(f"{path} has no dependencies")
    return pins


def wheel_identity(path: Path) -> tuple[str, str]:
    with zipfile.ZipFile(path) as archive:
        metadata_names = [
            name for name in archive.namelist() if name.endswith(".dist-info/METADATA")
        ]
        if len(metadata_names) != 1:
            raise ValueError(f"{path.name}: expected one wheel METADATA file")
        metadata = Parser().parsestr(
            archive.read(metadata_names[0]).decode("utf-8", errors="strict")
        )
    name = metadata.get("Name")
    version = metadata.get("Version")
    if not name or not version:
        raise ValueError(f"{path.name}: missing Name or Version metadata")
    return name, version


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def resolve_target(
    python_tag: str,
    architecture: str,
    destination: Path,
    *,
    interpreter: str = sys.executable,
) -> tuple[Artifact, ...]:
    platform_tag = ARCHITECTURES[architecture]
    command = [
        interpreter,
        "-m",
        "pip",
        "download",
        "--disable-pip-version-check",
        "--quiet",
        "--only-binary=:all:",
        "--platform",
        platform_tag,
        "--python-version",
        python_tag,
        "--implementation",
        "cp",
        "--abi",
        f"cp{python_tag}",
        "--dest",
        str(destination),
        "--requirement",
        str(INPUT_PATH),
    ]
    subprocess.run(command, cwd=REPO_ROOT, check=True, timeout=900)

    artifacts = []
    for path in sorted(destination.iterdir(), key=lambda item: item.name.lower()):
        if path.suffix.lower() != ".whl":
            raise ValueError(f"{path.name}: source distributions are forbidden")
        name, version = wheel_identity(path)
        artifacts.append(Artifact(name, version, path.name, file_sha256(path)))
    return tuple(artifacts)


def validate_resolution(
    artifacts: tuple[Artifact, ...],
    pins: dict[str, tuple[str, str]],
    target: str,
) -> None:
    resolved = {normalize_name(artifact.name): artifact for artifact in artifacts}
    if len(resolved) != len(artifacts):
        raise ValueError(f"{target}: resolver returned duplicate distributions")
    if set(resolved) != set(pins):
        missing = sorted(set(pins) - set(resolved))
        unexpected = sorted(set(resolved) - set(pins))
        raise ValueError(
            f"{target}: requirements.in is not the complete graph; "
            f"missing={missing}, unexpected={unexpected}"
        )
    for name, (_, expected_version) in pins.items():
        actual_version = resolved[name].version
        if actual_version != expected_version:
            raise ValueError(
                f"{target}: {name} resolved to {actual_version}, expected {expected_version}"
            )


def render_lock(
    pins: dict[str, tuple[str, str]],
    hashes: dict[str, set[str]],
    target_description: str,
) -> str:
    lines = [
        "# Generated by scripts/lock_dependencies.py from requirements.in.",
        f"# Target: {target_description}",
        "--only-binary=:all:",
        "--require-hashes",
        "",
    ]
    for normalized in sorted(pins):
        display_name, version = pins[normalized]
        package_hashes = sorted(hashes.get(normalized, ()))
        if not package_hashes:
            raise ValueError(f"No artifact hash for {display_name}")
        lines.append(f"{display_name}=={version} \\")
        for index, digest in enumerate(package_hashes):
            suffix = " \\" if index < len(package_hashes) - 1 else ""
            lines.append(f"    --hash=sha256:{digest}{suffix}")
    return "\n".join(lines) + "\n"


def atomic_write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
    )
    try:
        with os.fdopen(handle, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary_name, path)
    except Exception:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise


def generated_locks(interpreter: str = sys.executable) -> dict[Path, str]:
    pins = read_input_pins()
    outputs: dict[Path, str] = {}
    aggregate_hashes = {name: set() for name in pins}

    with tempfile.TemporaryDirectory(prefix="msstorehelper-locks-") as temp_root:
        temp_path = Path(temp_root)
        for python_tag in PYTHON_TAGS:
            for architecture in ARCHITECTURES:
                target = f"cp{python_tag}-{architecture}"
                destination = temp_path / target
                destination.mkdir()
                artifacts = resolve_target(
                    python_tag, architecture, destination, interpreter=interpreter
                )
                validate_resolution(artifacts, pins, target)
                target_hashes = {name: set() for name in pins}
                for artifact in artifacts:
                    normalized = normalize_name(artifact.name)
                    target_hashes[normalized].add(artifact.sha256)
                    aggregate_hashes[normalized].add(artifact.sha256)
                minor = f"{python_tag[0]}.{python_tag[1:]}"
                lock_path = LOCK_ROOT / f"windows-cp{python_tag}-{architecture}.txt"
                outputs[lock_path] = render_lock(
                    pins,
                    target_hashes,
                    f"CPython {minor} on Windows {architecture}",
                )

    outputs[REPO_ROOT / "requirements.txt"] = render_lock(
        pins,
        aggregate_hashes,
        "CPython 3.11-3.14 on Windows x64, x86, and ARM64",
    )
    return outputs


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if committed lock files differ from a fresh resolution",
    )
    args = parser.parse_args(argv)

    outputs = generated_locks()
    changed = []
    for path, content in outputs.items():
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        changed.append(path)
        if not args.check:
            atomic_write_text(path, content)

    if args.check and changed:
        for path in changed:
            print(f"stale lock: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
        return 1
    if changed:
        print(f"updated {len(changed)} dependency lock files")
    else:
        print("dependency locks are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
